# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
# - stage: Build
#   displayName: Build and push stage
#   jobs:  
#   - job: Build
#     displayName: Build job
#     pool:
#       vmImage: ubuntu-latest
#     steps:
    
    # - task: AzureCLI@1
    #   displayName: Acr name
    #   inputs:
    #     azureSubscription: AZURE_CREDENTIALS
    #     scriptLocation: inlineScript
    #     inlineScript: |
    #         az acr login -n $(acrName)             
    # - task: Bash@3
    #   displayName: Build and Push App
    #   inputs:
    #     targetType: 'inline'
    #     workingDirectory: "src"
    #     script: |
    #          docker build -f Dockerfile -t $(acrName).azurecr.io/webappdeploymentdemoapp:$(Build.SourceVersion) .
    #          docker push $(acrName).azurecr.io/webappdeploymentdemoapp:$(Build.SourceVersion)

- stage: DEV
  displayName: DEV
  jobs:  
  - job: Dev
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AZURE_CREDENTIALS'
        subscriptionId: 'ed9abfff-56b6-4ed3-b659-f66b213ab94a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'webappbestpractices-borjagr-1234'
        location: 'North Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'deployment/azuredeploy.appserviceoncontainers.json'
        overrideParameters: '-acrName $(acrName) -image webappdeploymentdemoapp -TAG $(Build.SourceVersion)'
        deploymentMode: 'Incremental'

    # - task: AzureCLI@1
    #   displayName: PullRole
    #   inputs:
    #     azureSubscription: AZURE_CREDENTIALS
    #     scriptLocation: inlineScript
    #     inlineScript: |
    #       az role assignment create --assignee 3444b199-0f26-47cb-b62c-28aaad4d1894 --scope /subscriptions/ed9abfff-56b6-4ed3-b659-f66b213ab94a/resourceGroups/webappbestpractices-borjagr-1234/providers/Microsoft.ContainerRegistry/registries/webappbestpracticesacr --role AcrPull